[package]
name = "sorta-vault"
version = "1.0.0"
edition = "2021"
authors = ["Sorta Vault Core Team"]
description = "Sorta Auto-Compound Vault Protocol"
keywords = ["solana", "anchor", "sorta-vault"]
license = "MIT/Apache-2.0"
readme = "./README.md"

[dependencies]
anchor-lang = "0.24.2"
